<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TigiePartidaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TigiePartidaRepository extends EntityRepository
{
    public function findByCodigoQuery($q)
    {
        if (!$q || strlen($q) < 4)
            return [];

        $chapCode = substr($q,0,2);
        $partCode = substr($q,2,2);

        return $this->createQueryBuilder("p")
            ->where("p.numero = :pq")
            ->setParameter("pq", $partCode)
            ->leftJoin('p.capitulo', 'c')
            ->andWhere('c.capitulo = :cq')
            ->setParameter("cq", $chapCode)
            ->getQuery()
            ->getResult();
    }
}
