<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TigieSubpartidaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TigieSubpartidaRepository extends EntityRepository
{
    public function findByCodigoQuery($q)
    {
        if (!$q || strlen($q) < 6)
            return [];

        $chapCode = substr($q,0,2);
        $partCode = substr($q,2,4);
        $subpCode = substr($q,6,6);
        return $this->createQueryBuilder("s")
            ->where("s.numero = :sq")
            ->setParameter("sq", $subpCode)
            ->leftJoin('s.partida', 'p')
            ->andWhere('p.numero = :pq')
            ->setParameter("pq", $partCode)
            ->leftJoin('p.capitulo', 'c')
            ->andWhere('c.capitulo = :cq')
            ->setParameter("cq", $chapCode)
            ->getQuery()->getArrayResult();
    }
}
